# Generated by Django 5.1.3 on 2024-12-19 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0003_eatenfood_user_alter_eatenfood_food_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_meal', models.BooleanField(default=False)),
                ('calories', models.IntegerField()),
                ('serving_size', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='eatenfood',
            name='food',
        ),
        migrations.RemoveField(
            model_name='eatenfood',
            name='user',
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('ADD', 'Add'), ('COOK', 'Cook'), ('EAT', 'Eat'), ('DISPOSE', 'Dispose')], max_length=10)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('pantry_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessApp.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recipes', to='FitnessApp.item')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_recipes', to='FitnessApp.item')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecipe',
            fields=[
                ('user_recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ingredient_recipes', to='FitnessApp.item')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meal_recipes', to='FitnessApp.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='EatenFood',
        ),
    ]
