# Generated by Django 5.1.3 on 2024-12-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0004_item_remove_eatenfood_food_remove_eatenfood_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='carbs_fiber',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='carbs_starch',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='carbs_sugar',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='fats_saturated',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='fats_unsaturated',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
    ]
