# Generated by Django 5.1.3 on 2024-12-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0005_item_carbs_fiber_item_carbs_starch_item_carbs_sugar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='serving_size',
        ),
        migrations.RemoveField(
            model_name='pantry',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='userrecipe',
            name='unit',
        ),
        migrations.AddField(
            model_name='item',
            name='serving_weight',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
