# Generated by Django 5.1.3 on 2024-12-20 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0006_remove_action_unit_remove_item_serving_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='userrecipe',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='userrecipe',
            name='user',
        ),
        migrations.AddField(
            model_name='action',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions_as_ingredient', to='FitnessApp.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_as_item', to='FitnessApp.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='serving_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Pantry',
        ),
        migrations.DeleteModel(
            name='UserRecipe',
        ),
    ]
