# Generated by Django 5.1.3 on 2024-12-20 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0007_remove_userrecipe_ingredient_remove_userrecipe_meal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_calories', models.IntegerField(default=2000)),
                ('goal_protein', models.FloatField(default=150)),
                ('goal_carbs', models.FloatField(default=250)),
                ('goal_fats', models.FloatField(default=45)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
